# Generated by Django 3.2.7 on 2021-12-20 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_blogapp', '0002_blogs123'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs123s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
                ('desc', models.CharField(max_length=700)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='blogimg')),
            ],
        ),
    ]
