# Generated by Django 3.2.7 on 2021-12-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_blogapp', '0003_blogs123s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs123',
        ),
        migrations.DeleteModel(
            name='blogs123s',
        ),
    ]
