# Generated by Django 3.2.7 on 2021-12-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_blogapp', '0004_auto_20211220_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
    ]
