# Generated by Django 3.2.7 on 2021-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_blogapp', '0005_remove_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(null='true', upload_to='blogimg'),
            preserve_default='true',
        ),
    ]
